(() => {
  const translations = {
    "pt-BR": {
      "language.label": "Idioma", "nav.how": "Como funciona", "nav.features": "Recursos", "nav.releases": "Notas da versão", "nav.support": "Suporte", "nav.privacy": "Privacidade", "nav.download": "Baixar",
      "hero.eyebrow": "TWITCH PARA WINDOWS", "hero.title": "Suas lives favoritas,<br><em>sem perder o começo.</em>", "hero.text": "Monitore seus streamers favoritos e abra automaticamente a transmissão assim que ela começar.", "hero.download": "Baixar para Windows", "hero.notes": "Ver notas da versão", "hero.platform": "Windows 10/11 • 64-bit • v1.0.1", "hero.badge": "LIVE READY",
      "trust.one": "uma abertura<br>por transmissão", "trust.two": "canais favoritos<br>monitorados", "trust.three": "feito para<br>acompanhar você",
      "how.eyebrow": "SIMPLES DESDE O PRIMEIRO MINUTO", "how.title": "Como funciona", "how.install.title": "Instale", "how.install.text": "Baixe o instalador oficial para Windows e abra o aplicativo.", "how.connect.title": "Conecte sua Twitch", "how.connect.text": "Autorize sua conta pelo fluxo oficial da Twitch, sem senha armazenada.", "how.add.title": "Adicione canais", "how.add.text": "Escolha seus streamers favoritos e deixe o monitoramento acontecer.", "how.ready.title": "Pronto", "how.ready.text": "Quando uma live começa, você recebe a notificação e a transmissão abre uma vez.",
      "features.eyebrow": "PENSADO PARA O SEU RITMO", "features.title": "Recursos", "features.intro.title": "Fique por perto<br>do que importa.", "features.intro.text": "Um cantinho leve no Windows para acompanhar as lives que você não quer perder.", "features.channels": "Canais favoritos monitorados", "features.eventsub": "Twitch EventSub oficial", "features.once": "Uma abertura por transmissão", "features.startup": "Inicia com o Windows", "features.tray": "Bandeja e notificações", "features.browsers": "Google Chrome, Microsoft Edge, Mozilla Firefox, Opera, Opera GX e navegador padrão",
      "managed.eyebrow": "JANELA GERENCIADA", "managed.title": "A transmissão fica no lugar certo.", "managed.text": "Quando um canal entra ao vivo, o Lazy Live Watcher abre a transmissão em uma janela própria no navegador selecionado. Quando a live termina, somente essa janela gerenciada é fechada.", "modes.window.title": "Janela própria do navegador", "modes.window.text": "A transmissão abre em uma janela gerenciada no navegador selecionado.", "modes.managed.title": "Fechamento seguro", "modes.managed.text": "As demais abas e janelas do navegador permanecem abertas.",
      "privacy.eyebrow": "SEUS DADOS FICAM COM VOCÊ", "privacy.title": "Privacidade,<br><em>sem complicação.</em>", "privacy.text": "O Lazy Live Watcher é um aplicativo local. Ele não precisa de uma conta própria, servidor ou coleta silenciosa para fazer o seu trabalho.", "privacy.more": "Leia a política de privacidade →", "privacy.local": "Aplicativo local", "privacy.noTracking": "Sem telemetria ou analytics", "privacy.noServer": "Sem servidor próprio", "privacy.official": "Autenticação oficial da Twitch", "privacy.noPassword": "Nenhuma senha Twitch armazenada",
      "next.eyebrow": "VERSÃO ATUAL", "next.title": "Novidades da versão atual", "next.text": "A versão 1.0.1 já está publicada. Confira as melhorias incluídas nesta versão.", "next.button": "Ver notas da versão", "download.eyebrow": "PRONTA PARA A PRÓXIMA LIVE?", "download.title": "Não perca o começo. ♡", "download.text": "Baixe a versão pública oficial do Lazy Live Watcher para Windows.", "download.button": "Baixar v1.0.1",
      "pages.privacy.eyebrow": "TRANSPARÊNCIA EM PRIMEIRO LUGAR", "pages.privacy.title": "Privacidade clara, sem letras pequenas.", "pages.privacy.intro": "O Lazy Live Watcher foi pensado para funcionar localmente no seu Windows, usando os serviços oficiais necessários para monitorar a Twitch.", "pages.support.eyebrow": "ESTAMOS AQUI PARA AJUDAR", "pages.support.title": "Suporte simples para o dia a dia.", "pages.support.intro": "Confira as respostas para as dúvidas mais comuns sobre instalação, conexão e monitoramento.", "pages.changelog.eyebrow": "HISTÓRICO DO PRODUTO", "pages.changelog.title": "Notas da versão", "pages.changelog.intro": "Histórico público e melhorias do Lazy Live Watcher.",
      "privacy.auth.title": "Autenticação Twitch", "privacy.auth.text": "A conta é conectada pelo fluxo oficial da Twitch. O aplicativo não pede nem armazena sua senha Twitch.", "privacy.storage.title": "Dados locais", "privacy.storage.text": "Canais, preferências e tokens necessários ficam armazenados localmente; os tokens são protegidos pelo Windows DPAPI.", "privacy.collection.title": "Sem coleta de comportamento", "privacy.collection.text": "Não usamos analytics, telemetria, publicidade, venda de dados ou servidor próprio para acompanhar o uso.", "privacy.window.title": "Janelas gerenciadas", "privacy.window.text": "O aplicativo acompanha apenas a janela própria que criou para a transmissão; as demais abas e janelas continuam sob seu controle.",
      "support.install.title": "Instalação", "support.install.text": "Baixe o instalador oficial da Release v1.0.1 e siga o assistente do Windows.", "support.twitch.title": "A Twitch não conecta", "support.twitch.text": "Confirme sua conexão com a internet, clique em Conectar com Twitch e conclua o fluxo oficial de autorização no navegador.", "support.channel.title": "Uma live não abre", "support.channel.text": "Confira o canal, o navegador selecionado e se a abertura automática está habilitada.", "support.browser.title": "Navegador selecionado", "support.browser.text": "Escolha o navegador nas configurações do aplicativo. São compatíveis Chrome, Edge, Firefox, Opera, Opera GX e o navegador padrão.", "support.managed.title": "Janela gerenciada", "support.managed.text": "A transmissão abre em uma janela própria. Quando termina, somente essa janela é fechada.", "support.startup.title": "Iniciar com o Windows", "support.startup.text": "Ative a opção correspondente em Configurações. O aplicativo usa apenas a entrada de inicialização criada por ele.", "support.notifications.title": "Notificações", "support.notifications.text": "Verifique se Mostrar notificações está habilitado no aplicativo e nas configurações de notificações do Windows.", "support.update.title": "Atualizações", "support.update.text": "Use Verificar atualizações em Configurações. Downloads de atualização são validados por SHA-256 antes da instalação.",
      "faq.title": "Perguntas frequentes", "faq.open.title": "O programa precisa ficar aberto?", "faq.open.text": "Sim. Ele pode ficar minimizado ou na bandeja para continuar monitorando.", "faq.limit.title": "Quantos canais posso adicionar?", "faq.limit.text": "A versão atual permite monitorar até 15 canais.", "faq.auto.title": "O Lazy Live Watcher abre a live sozinho?", "faq.auto.text": "Sim, quando a transmissão começa e a abertura automática está habilitada.", "faq.browser.title": "Quais navegadores funcionam?", "faq.browser.text": "Google Chrome, Microsoft Edge, Mozilla Firefox, Opera, Opera GX e o navegador padrão.", "faq.managed.title": "Como a live é aberta?", "faq.managed.text": "A transmissão é aberta em uma janela própria no navegador selecionado.", "faq.close.title": "Quando a live termina, o navegador inteiro fecha?", "faq.close.text": "Não. O Lazy Live Watcher fecha somente a janela gerenciada que ele próprio criou. As demais abas e janelas permanecem abertas.", "faq.data.title": "Meus dados são enviados para algum servidor?", "faq.data.text": "O aplicativo não usa servidor próprio, analytics ou telemetria. A autenticação e as APIs oficiais da Twitch são usadas apenas para a função solicitada.", "faq.free.title": "O aplicativo é gratuito?", "faq.free.text": "A versão pública 1.0.1 é distribuída gratuitamente.",
      "changelog.101.status": "PUBLICADA", "changelog.101.date": "Versão pública atual", "changelog.100.status": "PUBLICADA", "changelog.100.date": "Versão pública anterior", "changelog.new": "Novo", "changelog.improvements": "Melhorias", "changelog.fixes": "Correções", "changelog.101.intro": "A versão pública atual do Lazy Live Watcher.", "changelog.100.intro": "A primeira versão pública do Lazy Live Watcher para Windows.", "changelog.101.new": "Interface reformulada com layout compacto inspirado na versão original; lista de canais com rolagem própria; suporte a Português (Brasil), English e Español.", "changelog.101.improvements": "Até 15 canais; navegador selecionável; abertura em janela gerenciada; fechamento seguro; suporte a Chrome, Edge, Firefox, Opera e Opera GX; updater integrado; melhorias no EventSub, polling, responsividade e estabilidade.", "changelog.101.fixes": "Correções de startup, ComboBox, popups e jitter; logs de inicialização; preservação de configurações; melhorias no instalador e desinstalador; fechamento seguro sem encerrar o navegador inteiro.", "changelog.100.new": "Monitoramento Twitch, autenticação oficial e abertura automática.", "changelog.100.improvements": "Bandeja, notificações e inicialização com Windows.", "changelog.100.fixes": "Ajustes da primeira distribuição pública.", "changelog.download": "Baixar a versão pública 1.0.0"
    },
    "en-US": {
      "language.label": "Language", "nav.how": "How it works", "nav.features": "Features", "nav.releases": "Release notes", "nav.support": "Support", "nav.privacy": "Privacy", "nav.download": "Download", "hero.eyebrow": "TWITCH FOR WINDOWS", "hero.title": "Your favorite streams,<br><em>without missing the start.</em>", "hero.text": "Monitor your favorite streamers and automatically open the stream as soon as it starts.", "hero.download": "Download for Windows", "hero.notes": "View release notes", "hero.platform": "Windows 10/11 • 64-bit • v1.0.1", "hero.badge": "LIVE READY", "trust.one": "one opening<br>per stream", "trust.two": "favorite channels<br>monitored", "trust.three": "made to<br>follow along",
      "how.eyebrow": "SIMPLE FROM THE FIRST MINUTE", "how.title": "How it works", "how.install.title": "Install", "how.install.text": "Download the official Windows installer and open the app.", "how.connect.title": "Connect Twitch", "how.connect.text": "Authorize your account through Twitch's official flow, with no password stored.", "how.add.title": "Add channels", "how.add.text": "Choose your favorite streamers and let monitoring do the work.", "how.ready.title": "Ready", "how.ready.text": "When a stream starts, you get a notification and it opens once.", "features.eyebrow": "MADE FOR YOUR RHYTHM", "features.title": "Features", "features.intro.title": "Stay close<br>to what matters.", "features.intro.text": "A lightweight Windows corner for the streams you do not want to miss.", "features.channels": "Favorite channels monitored", "features.eventsub": "Official Twitch EventSub", "features.once": "One opening per stream", "features.startup": "Starts with Windows", "features.tray": "Tray and notifications", "features.browsers": "Google Chrome, Microsoft Edge, Mozilla Firefox, Opera, Opera GX, and the default browser",
      "managed.eyebrow": "MANAGED WINDOW", "managed.title": "The stream stays in the right place.", "managed.text": "When a channel goes live, Lazy Live Watcher opens the stream in its own managed browser window. When the stream ends, only that managed window is closed.", "modes.window.title": "The browser's own window", "modes.window.text": "The stream opens in a managed window in the selected browser.", "modes.managed.title": "Safe closing", "modes.managed.text": "The browser's other tabs and windows remain open.", "privacy.eyebrow": "YOUR DATA STAYS WITH YOU", "privacy.title": "Privacy,<br><em>without the fine print.</em>", "privacy.text": "Lazy Live Watcher is a local app. It does not need its own account, server, or silent collection to do its job.", "privacy.more": "Read the privacy policy →", "privacy.local": "Local application", "privacy.noTracking": "No telemetry or analytics", "privacy.noServer": "No own server", "privacy.official": "Official Twitch authentication", "privacy.noPassword": "No Twitch password stored",
      "next.eyebrow": "CURRENT VERSION", "next.title": "What's new in the current version", "next.text": "Version 1.0.1 is published. See what is included in this release.", "next.button": "View release notes", "download.eyebrow": "READY FOR THE NEXT STREAM?", "download.title": "Do not miss the start. ♡", "download.text": "Download the official public version of Lazy Live Watcher for Windows.", "download.button": "Download v1.0.1", "pages.privacy.eyebrow": "TRANSPARENCY FIRST", "pages.privacy.title": "Clear privacy, no fine print.", "pages.privacy.intro": "Lazy Live Watcher is designed to work locally on Windows, using only the official services needed to monitor Twitch.", "pages.support.eyebrow": "WE ARE HERE TO HELP", "pages.support.title": "Simple day-to-day support.", "pages.support.intro": "Find answers to common questions about installation, connection, and monitoring.", "pages.changelog.eyebrow": "PRODUCT HISTORY", "pages.changelog.title": "Release notes", "pages.changelog.intro": "Public history and improvements for Lazy Live Watcher.",
      "privacy.auth.title": "Twitch authentication", "privacy.auth.text": "Your account is connected through Twitch's official flow. The app never asks for or stores your Twitch password.", "privacy.storage.title": "Local data", "privacy.storage.text": "Channels, preferences, and required tokens stay local; tokens are protected by Windows DPAPI.", "privacy.collection.title": "No behavior collection", "privacy.collection.text": "We do not use analytics, telemetry, advertising, data sales, or an own server to track usage.", "privacy.window.title": "Managed windows", "privacy.window.text": "The app tracks only the window it created for the stream; your other tabs and windows remain under your control.", "support.install.title": "Installation", "support.install.text": "Download the official v1.0.1 release installer and follow the Windows wizard.", "support.twitch.title": "Twitch will not connect", "support.twitch.text": "Check your internet connection, click Connect with Twitch, and complete the official authorization flow in your browser.", "support.channel.title": "A stream will not open", "support.channel.text": "Check the channel, selected browser, and that automatic opening is enabled.", "support.browser.title": "Selected browser", "support.browser.text": "Choose the browser in the app settings. Chrome, Edge, Firefox, Opera, Opera GX, and the default browser are supported.", "support.managed.title": "Managed window", "support.managed.text": "The stream opens in its own window. When it ends, only that window is closed.", "support.startup.title": "Start with Windows", "support.startup.text": "Enable the option in Settings. The app only uses the startup entry it created.", "support.notifications.title": "Notifications", "support.notifications.text": "Check that notifications are enabled in the app and in Windows notification settings.", "support.update.title": "Updates", "support.update.text": "Use Check for updates in Settings. Update downloads are verified with SHA-256 before installation.",
      "faq.title": "Frequently asked questions", "faq.open.title": "Does the app need to stay open?", "faq.open.text": "Yes. It can stay minimized or in the tray to keep monitoring.", "faq.limit.title": "How many channels can I add?", "faq.limit.text": "The current version supports monitoring up to 15 channels.", "faq.auto.title": "Does Lazy Live Watcher open streams automatically?", "faq.auto.text": "Yes, when a stream starts and automatic opening is enabled.", "faq.browser.title": "Which browsers work?", "faq.browser.text": "Google Chrome, Microsoft Edge, Mozilla Firefox, Opera, Opera GX, and the default browser.", "faq.managed.title": "How is the stream opened?", "faq.managed.text": "The stream opens in its own window in the selected browser.", "faq.close.title": "When the stream ends, does the whole browser close?", "faq.close.text": "No. Lazy Live Watcher closes only the managed window it created. Other tabs and windows remain open.", "faq.data.title": "Is my data sent to a server?", "faq.data.text": "The app uses no own server, analytics, or telemetry. Official Twitch authentication and APIs are used only for the requested function.", "faq.free.title": "Is the app free?", "faq.free.text": "The public 1.0.1 version is distributed for free.", "changelog.101.status": "PUBLISHED", "changelog.101.date": "Current public version", "changelog.100.status": "PUBLISHED", "changelog.100.date": "Previous public version", "changelog.new": "New", "changelog.improvements": "Improvements", "changelog.fixes": "Fixes", "changelog.101.intro": "The current public release of Lazy Live Watcher.", "changelog.100.intro": "The first public version of Lazy Live Watcher for Windows.", "changelog.101.new": "Redesigned interface with a compact layout inspired by the original version; independently scrollable channel list; Portuguese (Brazil), English, and Spanish support.", "changelog.101.improvements": "Up to 15 channels; selectable browser; managed-window opening; safe closing; Chrome, Edge, Firefox, Opera, and Opera GX support; integrated updater; EventSub, polling, responsive, and stability improvements.", "changelog.101.fixes": "Startup, ComboBox, popup, and jitter fixes; startup logs; preserved settings; installer and uninstaller improvements; safe closing without shutting down the entire browser.", "changelog.100.new": "Twitch monitoring, official authentication, and automatic opening.", "changelog.100.improvements": "Tray, notifications, and start with Windows.", "changelog.100.fixes": "Fixes and adjustments for the first public distribution.", "changelog.download": "Download public version 1.0.0"
    },
    "es-419": {
      "language.label": "Idioma", "nav.how": "Cómo funciona", "nav.features": "Funciones", "nav.releases": "Notas de la versión", "nav.support": "Soporte", "nav.privacy": "Privacidad", "nav.download": "Descargar", "hero.eyebrow": "TWITCH PARA WINDOWS", "hero.title": "Tus transmisiones favoritas,<br><em>sin perder el comienzo.</em>", "hero.text": "Monitorea a tus streamers favoritos y abre automáticamente la transmisión cuando comience.", "hero.download": "Descargar para Windows", "hero.notes": "Ver notas de la versión", "hero.platform": "Windows 10/11 • 64-bit • v1.0.1", "hero.badge": "LIVE READY", "trust.one": "una apertura<br>por transmisión", "trust.two": "canales favoritos<br>monitoreados", "trust.three": "hecho para<br>acompañarte",
      "how.eyebrow": "SIMPLE DESDE EL PRIMER MINUTO", "how.title": "Cómo funciona", "how.install.title": "Instala", "how.install.text": "Descarga el instalador oficial para Windows y abre la aplicación.", "how.connect.title": "Conecta tu Twitch", "how.connect.text": "Autoriza tu cuenta mediante el flujo oficial de Twitch, sin guardar tu contraseña.", "how.add.title": "Agrega canales", "how.add.text": "Elige tus streamers favoritos y deja que el monitoreo haga su trabajo.", "how.ready.title": "Listo", "how.ready.text": "Cuando comienza una transmisión, recibes una notificación y se abre una vez.", "features.eyebrow": "PENSADO PARA TU RITMO", "features.title": "Funciones", "features.intro.title": "Quédate cerca<br>de lo importante.", "features.intro.text": "Un espacio ligero en Windows para acompañar las transmisiones que no quieres perder.", "features.channels": "Canales favoritos monitoreados", "features.eventsub": "Twitch EventSub oficial", "features.once": "Una apertura por transmisión", "features.startup": "Inicia con Windows", "features.tray": "Bandeja y notificaciones", "features.browsers": "Google Chrome, Microsoft Edge, Mozilla Firefox, Opera, Opera GX y navegador predeterminado",
      "managed.eyebrow": "VENTANA ADMINISTRADA", "managed.title": "La transmisión queda en el lugar correcto.", "managed.text": "Cuando un canal comienza una transmisión, Lazy Live Watcher la abre en una ventana administrada del navegador seleccionado. Cuando termina, solo se cierra esa ventana.", "modes.window.title": "Ventana propia del navegador", "modes.window.text": "La transmisión se abre en una ventana administrada del navegador seleccionado.", "modes.managed.title": "Cierre seguro", "modes.managed.text": "Las demás pestañas y ventanas del navegador permanecen abiertas.", "privacy.eyebrow": "TUS DATOS SE QUEDAN CONTIGO", "privacy.title": "Privacidad,<br><em>sin complicaciones.</em>", "privacy.text": "Lazy Live Watcher es una aplicación local. No necesita una cuenta propia, servidor ni recopilación silenciosa para funcionar.", "privacy.more": "Lee la política de privacidad →", "privacy.local": "Aplicación local", "privacy.noTracking": "Sin telemetría ni analytics", "privacy.noServer": "Sin servidor propio", "privacy.official": "Autenticación oficial de Twitch", "privacy.noPassword": "No se guarda la contraseña de Twitch",
      "next.eyebrow": "VERSIÓN ACTUAL", "next.title": "Novedades de la versión actual", "next.text": "La versión 1.0.1 ya está publicada. Mira las mejoras incluidas en esta versión.", "next.button": "Ver notas de la versión", "download.eyebrow": "¿LISTA PARA LA PRÓXIMA TRANSMISIÓN?", "download.title": "No pierdas el comienzo. ♡", "download.text": "Descarga la versión pública oficial de Lazy Live Watcher para Windows.", "download.button": "Descargar v1.0.1", "pages.privacy.eyebrow": "TRANSPARENCIA PRIMERO", "pages.privacy.title": "Privacidad clara, sin letra pequeña.", "pages.privacy.intro": "Lazy Live Watcher está diseñado para funcionar localmente en Windows, usando solo los servicios oficiales necesarios para monitorear Twitch.", "pages.support.eyebrow": "ESTAMOS PARA AYUDAR", "pages.support.title": "Soporte sencillo para el día a día.", "pages.support.intro": "Encuentra respuestas a preguntas comunes sobre instalación, conexión y monitoreo.", "pages.changelog.eyebrow": "HISTORIAL DEL PRODUCTO", "pages.changelog.title": "Notas de la versión", "pages.changelog.intro": "Historial público y mejoras de Lazy Live Watcher.",
      "privacy.auth.title": "Autenticación de Twitch", "privacy.auth.text": "Tu cuenta se conecta mediante el flujo oficial de Twitch. La aplicación nunca solicita ni guarda tu contraseña de Twitch.", "privacy.storage.title": "Datos locales", "privacy.storage.text": "Canales, preferencias y tokens necesarios permanecen localmente; los tokens están protegidos por Windows DPAPI.", "privacy.collection.title": "Sin recopilar comportamiento", "privacy.collection.text": "No usamos analytics, telemetría, publicidad, venta de datos ni un servidor propio para rastrear el uso.", "privacy.window.title": "Ventanas administradas", "privacy.window.text": "La aplicación solo supervisa la ventana que creó para la transmisión; tus demás pestañas y ventanas siguen bajo tu control.", "support.install.title": "Instalación", "support.install.text": "Descarga el instalador oficial de la versión 1.0.1 y sigue el asistente de Windows.", "support.twitch.title": "Twitch no conecta", "support.twitch.text": "Comprueba tu conexión, pulsa Conectar con Twitch y completa el flujo oficial de autorización en el navegador.", "support.channel.title": "Una transmisión no abre", "support.channel.text": "Comprueba el canal, el navegador seleccionado y que la apertura automática esté habilitada.", "support.browser.title": "Navegador seleccionado", "support.browser.text": "Elige el navegador en la configuración de la aplicación. Son compatibles Chrome, Edge, Firefox, Opera, Opera GX y el navegador predeterminado.", "support.managed.title": "Ventana administrada", "support.managed.text": "La transmisión se abre en su propia ventana. Cuando termina, solo se cierra esa ventana.", "support.startup.title": "Iniciar con Windows", "support.startup.text": "Activa la opción en Configuración. La aplicación solo usa la entrada de inicio que ella misma creó.", "support.notifications.title": "Notificaciones", "support.notifications.text": "Comprueba que Mostrar notificaciones esté activo en la aplicación y en las notificaciones de Windows.", "support.update.title": "Actualizaciones", "support.update.text": "Usa Buscar actualizaciones en Configuración. Las descargas se validan con SHA-256 antes de instalarse.",
      "faq.title": "Preguntas frecuentes", "faq.open.title": "¿La aplicación debe permanecer abierta?", "faq.open.text": "Sí. Puede quedarse minimizada o en la bandeja para seguir monitoreando.", "faq.limit.title": "¿Cuántos canales puedo agregar?", "faq.limit.text": "La versión actual permite monitorear hasta 15 canales.", "faq.auto.title": "¿Lazy Live Watcher abre las transmisiones automáticamente?", "faq.auto.text": "Sí, cuando comienza una transmisión y la apertura automática está habilitada.", "faq.browser.title": "¿Qué navegadores funcionan?", "faq.browser.text": "Google Chrome, Microsoft Edge, Mozilla Firefox, Opera, Opera GX y el navegador predeterminado.", "faq.managed.title": "¿Cómo se abre la transmisión?", "faq.managed.text": "La transmisión se abre en una ventana propia del navegador seleccionado.", "faq.close.title": "Cuando termina la transmisión, ¿se cierra todo el navegador?", "faq.close.text": "No. Lazy Live Watcher cierra solamente la ventana administrada que creó. Las demás pestañas y ventanas permanecen abiertas.", "faq.data.title": "¿Mis datos se envían a algún servidor?", "faq.data.text": "La aplicación no usa servidor propio, analytics ni telemetría. La autenticación y las APIs oficiales de Twitch se usan solo para la función solicitada.", "faq.free.title": "¿La aplicación es gratuita?", "faq.free.text": "La versión pública 1.0.1 se distribuye gratis.", "changelog.101.status": "PUBLICADA", "changelog.101.date": "Versión pública actual", "changelog.100.status": "PUBLICADA", "changelog.100.date": "Versión pública anterior", "changelog.new": "Nuevo", "changelog.improvements": "Mejoras", "changelog.fixes": "Correcciones", "changelog.101.intro": "La versión pública actual de Lazy Live Watcher.", "changelog.100.intro": "La primera versión pública de Lazy Live Watcher para Windows.", "changelog.101.new": "Interfaz renovada con un diseño compacto inspirado en la versión original; lista de canales con desplazamiento propio; compatibilidad con Portugués (Brasil), English y Español.", "changelog.101.improvements": "Hasta 15 canales; navegador seleccionable; apertura en ventana administrada; cierre seguro; compatibilidad con Chrome, Edge, Firefox, Opera y Opera GX; actualizador integrado; mejoras en EventSub, polling, responsividad y estabilidad.", "changelog.101.fixes": "Correcciones de inicio, ComboBox, popups y jitter; logs de inicio; preservación de configuración; mejoras del instalador y desinstalador; cierre seguro sin cerrar todo el navegador.", "changelog.100.new": "Monitoreo de Twitch, autenticación oficial y apertura automática.", "changelog.100.improvements": "Bandeja, notificaciones e inicio con Windows.", "changelog.100.fixes": "Correcciones y ajustes de la primera distribución pública.", "changelog.download": "Descargar la versión pública 1.0.0"
    }
  };

  const fallback = translations["pt-BR"];
  const languagePreferenceKey = "lazyLiveWatcher.language.v2";
  function valueFor(key) {
    const current = translations[document.documentElement.lang] || fallback;
    return current[key] || fallback[key] || key;
  }

  function applyLanguage(language, persist = false) {
    const selected = translations[language] ? language : "pt-BR";
    document.documentElement.lang = selected;
    if (persist) localStorage.setItem(languagePreferenceKey, selected);
    document.querySelectorAll("[data-i18n]").forEach((element) => {
      const value = valueFor(element.dataset.i18n);
      if (value.includes("<")) element.innerHTML = value;
      else element.textContent = value;
    });
    document.querySelectorAll("[data-language]").forEach((select) => {
      select.value = selected;
    });
  }

  document.addEventListener("DOMContentLoaded", () => {
    const saved = localStorage.getItem(languagePreferenceKey);
    const initialLanguage = translations[saved] ? saved : "pt-BR";
    document.querySelectorAll("[data-language]").forEach((select) => {
      select.addEventListener("change", () => applyLanguage(select.value, true));
    });
    applyLanguage(initialLanguage);
  });
})();
